### ISSUE TITLE
Serial/UART handshaking

### ISSUE THREAD

**Issue by mikewen** [aanon4/BlueBasic#12]
Love BlueBasic! Thanks!!!!

Right now, BlueBasic only support hardware handshaking
SERIAL 9600,N,8,1,H

This will give error:
SERIAL 9600,N,8,1,N

Here are the codes in OS_serial_open function (os.c ) :
// Only support port 0, no-parity, 8-bits, 1 stop bit
if (port != 0 || parity != 'N' || bits != 8 || stop != 1 || flow != 'H')
{
return 3;
}

**Comment by aanon4** [comment]
As far as I could tell reading the UART code from TI, they only support hardware handshaking.

**Comment by mikewen** [comment]
I changed the UART code from TI , and compiled .hex files with software handshaking support:
Here is link of my Fork with .hex files for download:
https://github.com/mikewen/BlueBasic

**Comment by aanon4** [comment]
Cool. Can you send me a patch?

**Comment by aanon4** [comment]
Or a pull request perhaps?
