### ISSUE TITLE
Unable to use P2_1 through P2_4 for output

### ISSUE THREAD

**Issue by jtagen** [aanon4/BlueBasic#14]
When I try to use P2_1 and later for output, get the message "Bad pin". Transcript of session below.

Thanks for creating this, I'm very excited!

BlueBasic CC2541/20150213105740/OAD v0.6
http://blog.xojs.org/bluebasic
7856 bytes free.
OK
PINMODE P2(0) OUTPUT
OK
P2(0) = 1
OK
PINMODE P2(1) OUTPUT
Bad pin
P2(1) = 1
Bad pin

**Comment by jtagen** [comment]
Ah, I see this now, assuming it's specific to your hardware (debug and ?clock?).

I'm one of the unfortunates with no IAR license. Any chance you can provide a generic hex with all pins enabled?

**Comment by aanon4** [comment]
True - I have specific hardware and excluded these in the builds. Might make sense to put them back for the basic 2540/1 builds and just exclude them for the Petra build (my hardware).

**Comment by aanon4** [comment]
Just updates the builds. The non-Petra builds should now allow access to all P2 pins. Let me know how it looks.

**Comment by jtagen** [comment]
Awesome, thank you!

**Comment by jtagen** [comment]
Thanks again, this worked perfectly.
