### ISSUE TITLE
Accessing pin 14/15 on 2541

### ISSUE THREAD

**Issue by jtagen** [aanon4/BlueBasic#16]
I'm trying to use BlueBasic on an existing device with I2C peripherals. Looks like they used the hardware I2C on pins 14/15. Possible to access these as general I/O pins ?

**Comment by aanon4** [comment]
I've been working with CC2540 chips which don't have the I2C hardware. I'm sure this is possible, but I have no plans to add it. I'd be happy to take a pull request if someone added support.
