### ISSUE TITLE
loading BlueBasic using this method possible?

### ISSUE THREAD

**Issue by lorneb** [aanon4/BlueBasic#20]
Hi excellent project, have been trying to load BlueBasic to a module for a couple of hours today.
this is the method I'm using https://github.com/RedBearLab/CCLoader

uses an arduino to act as a programmer.  
The module I am trying to update is a ble-cc41-a,  which has a cc2541 on it.

I was trying using the bin file for the cc2541 chip from you repo.  
it appears to flash ok, but cannot see any devices in the console.

Is the .bin from this repo comptable do you think?
Is there are way to check that code is running, debug output from module on serial ?

thanks in advance

**Comment by crushedice2000** [comment]
If you can detect the device immediately after reset and then it stops advertising, it can be a problem with a missing xtal.

**Comment by 0xFACE** [comment]
Seems to be problem with missing 32kHz external crystal.
Interesting topic here: https://e2e.ti.com/support/wireless_connectivity/f/538/t/398466

**Comment by crushedice2000** [comment]
@aanon4: You **should** build the binaries with this preprocessor directive:

CC2450: `XOSC32K_INSTALLED=FALSE`
CC2541: `OSC32K_CRYSTAL_INSTALLED=FALSE`

**Comment by lorneb** [comment]
@aanon4 Could you please produce to more build outputs with the above suggestions?
TIA

**Comment by aanon4** [comment]
Unfortunately I no longer have access to either the hardware or the tools to make any new builds. Sorry.

**Comment by 0x2b3bfa0** [comment]
@aanon4: I figured it out. However, could you leave open this issue and simply edit README.md to explain that? Maybe I can fix this in a non-so-far future.

Thank you very much! Your project is amazing!

Don't worry by the support lack.
