### ISSUE TITLE
Wiki typo on "Pin names and uses"

### ISSUE THREAD

**Issue by 0x2b3bfa0** [aanon4/BlueBasic#22]
On this wiki page, the last line of the table says P1(4) instead of P2(4)

https://github.com/aanon4/BlueBasic/wiki/Pin-names-and-uses

I can't find how to edit this wiki :-(

**Comment by JBtje** [comment]
You cant. You could copy all and create your own wiki.
Or use my wiki, updated, more info and more examples...
https://github.com/JBtje/BlueBasic/wiki/Pin-names-and-uses

**Comment by 0x2b3bfa0** [comment]
@JBtje: Ok, thanks!

**Comment by aanon4** [comment]
Fixed

**Comment by 0x2b3bfa0** [comment]
@aanon4: Thank you!
