### ISSUE TITLE
Pins and names CC2540

### ISSUE THREAD

**Issue by gregwinn** [aanon4/BlueBasic#5]
Based on your wiki page: "https://github.com/aanon4/BlueBasic/wiki/Pin-names-and-uses"

You are showing

```
P0_2 -> RX
P0_3 -> TX
```

Based on TI's information i show them as:

```
P0_2 -> MISO
P0_3 -> MOSI
```

Am i getting something wrong?

**Comment by mikewen** [comment]
Are you sure 9600,N,8,1,N work?

I tried SERIAL 9600,N,8,1,N , console shows Error,
then I looked at : OS_serial_open
// Only support port 0, no-parity, 8-bits, 1 stop bit
  if (port != 0 || parity != 'N' || bits != 8 || stop != 1 || flow != 'H')
  {
    return 3;
  }

**Comment by mikewen** [comment]
Can you let me know what the 'Not in direct' means?

In Console:
BlueBasic CC2540/20150104225856/OAD v0.6
http://blog.xojs.org/bluebasic
8176 bytes free.
OK
SERIAL 9600,N,8,1,H
OK
WRITE #0,"A"
Not in direct

**Comment by aanon4** [comment]
Apparently not :-(
