### ISSUE TITLE
Console App OSX

### ISSUE THREAD

**Issue by paulsponagl** [aanon4/BlueBasic#9]
Hi Tim,
tested the HM-10 flashing with cc debugger - seemed to work. now i thought of using the
https://github.com/aanon4/BlueBasic/blob/master/Console/Blue%20Basic.zip
you mentioned / not found / ok / try to build it / oh swift / xcode 4.x on my macbook pro ...
puh - that would be heavy install stuff (os upgrade/xcode upgrade ...)
do you have a working binary for osx lion (10.7.5) somewhere around ?
Best
Paul

**Comment by crushedice2000** [comment]
@aanon4, can you put the link to the android app? I don't have a OS X nor iOS device now...

Thanks.

**Comment by yaccard** [comment]
Hello
I am also interested in BlueBasic console for Android (or linux or Windows).
Best regards
Yves

**Comment by crushedice2000** [comment]
@yaccard: https://github.com/0xFACE/BlueBasic-loader

**Comment by jzeeff** [comment]
That's a loader, but I have yet to see a console app for android that will talk to BlueBasic.  It's a shame, since BlueBasic sounds interesting.
